### ISSUE TITLE
fbi not installed

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#1]
(This note originally applied to the mistserver based setup, but it might be useful to use some of the same components for the voctomix based one...)
Hey,

Journalctl -b turns up a lot of failed attempts at using fbi - Linux frame buffer image viewer, like this:
`Sep 19 04:15:44 aw1125cam fosbox_collect[14826]: /usr/local/bin/fosbox_collect: line 13: fbi: command not found
`

You might want to add the package "fbida" to the pacman tasks. Or not, if this is just a remainder of something past that should be cleaned up of course.

**Comment by gerryd** [comment]
Irrelevant now.
