### ISSUE TITLE
sound ingestion: filters

### ISSUE THREAD

**Issue by krokodilerian** [FOSDEM/video#100]
After a talk last night, we can steal an idea from nageru - a simple audio filter chain:
- low-cut filter (everything below 120hz is removed)
- slow compressor to set the overall level
- fast compressor
- limiter not to start clipping
(as explained in https://www.youtube.com/watch?v=ZRTS503KnQw&feature=youtu.be&t=765 )

This should be easy to put in the ffmpeg that ingests the camera feed (where our sound it). It will need to be tested with different types of noise.

**Comment by zeridon** [comment]
Add also situations where DI-Box or similar is needed to the test list

**Comment by zeridon** [comment]
A bit more detailed explanation for the reasons behind the audio staging chosen for nageru https://git.sesse.net/?p=nageru-docs;a=blob;f=audio.rst;h=58e3ed07a71df0f3d11c2dc144e8f5ac1abfe4c6;hb=HEAD#l122

**Comment by markvdb** [comment]
Proper input using all sennheiser avx series mics from 2019 will fix this.
