### ISSUE TITLE
'no talk' animations

### ISSUE THREAD

**Issue by yoe** [FOSDEM/video#101]
Other conferences (Debconf, CCC, FOSDEM in 2011-2014) have an animation loop that can be played between talks. Usually, such a loop shows a short animation of the conference logo etc, and is then followed by sponsor logos.

Having such animation loops are advantageous for viewers too, as they can more easily see that a particular stream does not currently show interesting content. With voctomix, it is also possible to show a sponsor loop on the stream while still recording the camera and slides (in case the room operator forgets to switch it off)

Do we want this for 2018?

**Comment by kergon** [comment]
> Do we want this for 2018?

Yes!

**Comment by krokodilerian** [comment]
With the current flow, this is impossible. Voctomix itself has this functionality and we can easily add interface to it, but there isn't anyone who can switch between the live and pause streams - this will be another requirement for the devroom managers, or there will be a need for dedicated video directors to handle this from the NOC.

**Comment by yoe** [comment]
I don't think it's necessarily bad that some rooms don't ever switch to the sponsor loop, just like it's not necessarily bad that some rooms don't ever change away from the default PIP layout with slides on the large part of the screen and camera on the small part...

**Comment by krokodilerian** [comment]
The problem is not that they don't switch to it, but that they won't switch back. On all the others the sound is from the room, so whatever happens, it's still somewhat useful, with this there won't even be audio.

If enough people are interested, it should be possible to make one such flickerless loop and push it on all laptops, it'll fit in memory and will work fine, basically the same as the background.

**Comment by yoe** [comment]
> The problem is not that they don't switch to it, but that they won't switch back. On all the others the sound is from the room, so whatever happens, it's still somewhat useful, with this there won't even be audio.

Ah yes, good point; hadn't thought of that. I suppose we could implement a time limit on the loop so that it automatically switches back to the default state, but then that might be way too complicated and not worth it.

> If enough people are interested, it should be possible to make one such flickerless loop and push it on all laptops, it'll fit in memory and will work fine, basically the same as the background.

As a data point, I have built several such animations (all FOSDEM animations in the past, DebConf 13, DebConf 16), and I'd be happy to build another one next year if needs be.

But I agree that there are practical considerations and that we may need to decide not to do it.

**Comment by markvdb** [comment]
Not doing this for lack of manpower.
