### ISSUE TITLE
timezone indication on streaming schedule

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#103]
See https://blog.sesse.net/blog/tech/2017-08-05-11-40_dear_conference_organizers.html .

**Comment by gerryd** [comment]
I think this is about https://fosdem.org/2019/schedule/streaming/ so this is actually a website issue.

**Comment by markvdb** [comment]
Website issue. Seems to have been fixed or at least has a pull request at https://github.com/FOSDEM/website/pull/152 .
