### ISSUE TITLE
keep an eye on vp9 support

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#104]
http://www.cnx-software.com/2017/08/13/new-features-of-intel-gemini-lake-processors-hdmi-2-0-10-bit-vp9-codec-4-way-pipeline-and-more/ seems to suggest upcoming vp9 decoding ánd encoding support in low end, low power intel cpus.

**Comment by SuperQ** [comment]
A number of the recent ARM SBCs can do vp9 as well.

**Comment by yoe** [comment]
On Sun, Aug 13, 2017 at 02:14:59PM +0000, Mark Van den Borre wrote:
> http://www.cnx-software.com/2017/08/13/
> new-features-of-intel-gemini-lake-processors-hdmi-2-0-10-bit-vp9-codec-4-way-pipeline-and-more
> / seems to suggest upcoming vp9 decoding ánd encoding support in low end, low
> power intel cpus.

If we're going to stream in VP9, that's cool, but I suspect impossible.

If we're going to transcode to VP9, I think we'll need half a second of
video data per second of wall-clock encoding time for this to be
feasible.

Other than that, go wild :-)

-- 
Could you people please use IRC like normal people?!?

  -- Amaya Rodrigo Sastre, trying to quiet down the buzz in the DebConf 2008
     Hacklab

**Comment by yoe** [comment]
In the context of the DebConf17 videos, I recently found <https://developers.google.com/media/vp9/>, which explains how to do VP9 encoding in a reasonable (i.e., not insanely slow) way.

Unfortunately, some bugs in the ffmpeg version in Debian 9 were exposed while testing this, which might mean we can't actually use this properly yet. Also, firefox seems to fail to play such files; not sure exactly why that is.

At any rate, this might be something to investigate.

**Comment by krokodilerian** [comment]
In terms of plugging this into the existing system, if we can have some spare CPU on the restreamers to pull the h264 streams and push them back to a different server (afaik icecast), we can have some kind of vp9 support. It should be possible to have it only for one room this year, to test how it behaves.

I'll put it on my list to look into later.

**Comment by yoe** [comment]
For reference, there were no bugs in Debian 9's ffmpeg. There were some surprises though, which lead to "no video in Firefox" in a few cases.

The plain and simple version is that VP9 supports more pixel formats than does VP8 and Firefox, and you can't have YUV422 (YUV420 is fine). We already set that for our MP4 streams, so this should not be an issue for Firefox.

If we select the ffmpeg options for streaming that Google suggests in the link that I posted earlier (and we have the CPU power), we should be able to provide VP9 streams just fine.

**Comment by yoe** [comment]
I'm assuming that moving this to 2019 is done just because we won't be streaming VP9 for the 2018 edition. For reference, SReview will output VP9 files (and I'll disable the VP8 output)

**Comment by markvdb** [comment]
Streaming vp9 is still too expensive in terms of cpu. Check next year.

**Comment by abitrolly** [comment]
So what was the streaming setup for FOSDEM 2023? Recorded videos include VP9 (https://fosdem.org/2023/schedule/event/nasa/).

**Comment by markvdb** [comment]
The published videos are vp9. Not going to do streaming in vp9 for the foreseeable future.
