### ISSUE TITLE
voctocore doesn't like our incoming video streams...

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#107]
<pre>ii  ffmpeg                    10:3.3.4-dmo1+deb amd64             audio/video encoder, streaming server & audio/video file
ii  gstreamer1.0-alsa:amd64   1.10.4-1          amd64             GStreamer plugin for ALSA
un  gstreamer1.0-audiosink    <none>            <none>            (no description available)
un  gstreamer1.0-audiosource  <none>            <none>            (no description available)
un  gstreamer1.0-libav        <none>            <none>            (no description available)
ii  gstreamer1.0-plugins-bad: 1:1.10.4-dmo2     amd64             GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-base 1.10.4-1          amd64             GStreamer plugins from the "base" set
un  gstreamer1.0-plugins-faac <none>            <none>            (no description available)
ii  gstreamer1.0-plugins-good 1.10.4-1          amd64             GStreamer plugins from the "good" set
un  gstreamer1.0-plugins-mpeg <none>            <none>            (no description available)
ii  gstreamer1.0-plugins-ugly 1:1.10.4-dmo1     amd64             GStreamer plugins from the "ugly" set
ii  gstreamer1.0-tools        1.10.4-1          amd64             Tools for use with GStreamer
un  gstreamer1.0-videosink    <none>            <none>            (no description available)
un  gstreamer1.0-videosource  <none>            <none>            (no description available)
un  gstreamer1.0-visualizatio <none>            <none>            (no description available)
ii  gstreamer1.0-x:amd64      1.10.4-1          amd64             GStreamer plugins for X11 and Pango
ii  voctomix                  0.6-1             all               Full-HD Software Live-Video-Mixer
</pre>

<pre>   DEBUG root: running Voctocore
    INFO Voctocore: running GObject-MainLoop
    INFO AVSource[cam1]: Incomming Connection from ('::1', 57624, 0, 0)
   DEBUG AVSource[cam1]: Launching Source-Pipeline:

            fdsrc fd=51 blocksize=1048576 !
            queue !
            matroskademux name=demux
        
                demux. !
                audio/x-raw,format=S16LE,channels=2,layout=interleaved,rate=48000 !
                queue !
                tee name=atee
            
                    atee. ! queue ! interaudiosink channel=audio_cam1_mixer
                
                    atee. ! queue ! interaudiosink channel=audio_cam1_mirror
                
                demux. !
                video/x-raw,format=I420,width=1280,height=720,framerate=25/1,pixel-aspect-ratio=1/1 !
                queue !
                tee name=vtee
            
                    vtee. ! queue ! intervideosink channel=video_cam1_mixer
                
                    vtee. ! queue ! intervideosink channel=video_cam1_mirror
                
   DEBUG AVSource[cam1]: Binding End-of-Stream-Signal on Source-Pipeline
   DEBUG AVSource[cam1]: demuxer added pad w/ caps: video/x-raw, format=(string)I420, width=(int)1280, height=(int)720, interlace-mode=(string)mixed, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2, colorimetry=(string)bt709, framerate=(fraction)25/1
   DEBUG AVSource[cam1]: new demuxer-pad is a video-pad, testing against configured video-caps
   DEBUG AVSource[cam1]: demuxer added pad w/ caps: audio/x-raw, format=(string)S16LE, layout=(string)interleaved, channel-mask=(bitmask)0x0000000000000003, channels=(int)2, rate=(int)48000
   DEBUG AVSource[cam1]: new demuxer-pad is a audio-pad, testing against configured audio-caps

** (python3:1159): CRITICAL **: gst_video_converter_new: assertion 'in_info->interlace_mode == out_info->interlace_mode' failed

** (python3:1159): CRITICAL **: gst_video_converter_frame: assertion 'convert != NULL' failed

** (python3:1159): CRITICAL **: gst_video_converter_free: assertion 'convert != NULL' failed
   DEBUG VideoMix: Received Error-Signal on Mixing-Pipeline
   DEBUG VideoMix: Error-Details: #1: gstbasesrc.c(2950): gst_base_src_loop (): /GstPipeline:pipeline2/GstInterVideoSrc:intervideosrc3:
streaming stopped, reason not-negotiated (-4)
</pre>

This seems to be very much related to https://github.com/voc/voctomix/issues/137 - bug in all current gstreamer versions...

Voctocore.ini contents:
<pre>
[mix]
videocaps=video/x-raw,format=I420,width=1280,height=720,framerate=25/1,pixel-aspect-ratio=1/1
audiocaps=audio/x-raw,format=S16LE,channels=2,layout=interleaved,rate=48000

; tcp-ports will be 10000,10001,10002
sources=cam1,grabber

; set the initial audio source
audiosource=cam1

[output-buffers]
; voctocore has a buffer on all video-outputs, that store video-frames for your
; sink when it can't handle them all in real-time. so if your sink takes 2 seconds
; to process a really hard to precess frame, voctomix needs to store 50 frames
; for you, hoping that your sink will catch up soon.
; if the sink doesn ot catch up in time, voctomix will drop it and remove it
; from the output. it's your task to restart it in such a situation.
; by default, voctomix will store up to 500 frames for your sink (20 seconds)
; you might want to up that even more for your recording-sink, so that it never
; gets disconnected. for this reason, the following configuration raises the
; default limit for the mix_out sink to a whopping 10'000 frames (400 seconds)
;cam1_mirror=500
;cam2_mirror=500
;grabber_mirror=500
mix_out=10000
;streamblanker_out=500

voctocore.ini
[fullscreen]
; if configured, switching to fullscreen will automatically select this
; source. if not configured, it will not change the last set source
;default-a=cam1

[side-by-side-equal]
; defaults to 1% of the video width
;gutter=12
;atop=50
;btop=200

; if configured, switching to the sbs-equal mode will automatically select these
; sources. if not configured, it will not change the last set sources
;default-a=cam1
;default-b=cam2

[side-by-side-preview]
;asize=1024x576
;apos=12/12
;bsize=320x180
;bpos=948/528

; automatically select these sources when switching to sbs-preview
;default-a=grabber
;default-b=cam1

[picture-in-picture]
;pipsize=320x180
;pippos=948/528

; automatically select these sources when switching to pip
;default-a=grabber
;default-b=cam1

[previews]
; disable if ui & server run on the same computer and can exchange uncompressed video frames
enabled=false
deinterlace=false

; use vaapi to encode the previews, can be h264, mpeg2 or jpeg (BUT ONLY h264 IS TESTED)
; not all encoders are available on all CPUs
;vaapi=h264

; default to mix-videocaps, only applicable if enabled=true
; you can change the framerate and the width/height, but nothing else
;videocaps=video/x-raw,width=1024,height=576,framerate=25/1

[stream-blanker]
enabled=false
sources=pause,nostream
</pre>

Incast script. Notice the -field_order progressive bit...
<pre>
#!/bin/sh

confdir="`dirname "$0"`/../config/"
. ${confdir}/defaults.sh
. ${confdir}/config.sh

ffmpeg -y -nostdin \
	-i "${SOURCE_CAM}${SOURCE_URL_PARAMETERS}" \
	-field_order progressive \
	-ac 2 \
	-filter_complex "
		[0:v] scale=$WIDTH:$HEIGHT,fps=$FRAMERATE,setdar=16/9,setsar=1 [v] ;
		[0:a] aresample=$AUDIORATE [a]
	" \
	-map "[v]" -map "[a]" \
	-pix_fmt yuv420p \
	-c:v rawvideo \
	-c:a pcm_s16le \
	-f matroska \
	tcp://localhost:10000
</pre>

**Comment by markvdb** [comment]
https://github.com/voc/multiview-monitor/commit/bae4e4e2480163bdf7d33b0dd8a02a7bc0f843c8 seems to provide inspiration on how to stopgap fix this ...

**Comment by markvdb** [comment]
Yep, adding this in the right place is a quick and dirty fix.

I included the above addition to the voctocore gstreamer ingestion pipeline bit in /usr/share/voctomix/voctocore/lib/sources/avsource.py (0.6, line 63, in front of ! intervideosink) and we have video again.

Now let's hope for a quick fix for this in Debian...
 needs the above included and video is working again!

**Comment by a-tze** [comment]
I think you put the "-field_order" to much in the front of the FFmpeg line. Try to put it right before "-f matroska", just for the lulz ;)

**Comment by markvdb** [comment]
Thx a-tze for the input. What bit us was the incasts. They got ignored for incasts, even with the -field_order progressive in the right place. Inspired by multiview-monitor, I just patched avsource.py to set progressive mode explicitly. See https://github.com/FOSDEM/infrastructure/blob/1069ee5bfaa6c3330ac8a1c2f66b8dbfaa5339e3/ansible/playbooks/roles/voctop/files/patches/avsource.py#L63 .

Keeping this bug open because we obviously want to have the gstreamer bug patched or worked around in voctomix someday.

**Comment by markvdb** [comment]
Fixed in gstreamer 1.0RC1. Packaged version in Debian sid for now.
https://packages.qa.debian.org/v/voctomix/news/20171118T192450Z.html

**Comment by markvdb** [comment]
All in stretch backports now.
