### ISSUE TITLE
deploy totally new image to boxes?

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#112]
We want to be able to programmatically deploy a totally new image to the boxes from scratch. How do we do that?

Totally new image means things like vanilla Debian stretch install with mainline kernel. We have ssh into the boxes and keys on them.

I remember doing a tricky manual crossgrade from Redhat to Debian on a server I didn't have a console on a few centuries ago, but that will not bring us very far... Any ideas?

https://wiki.debian.org/Debootstrap
https://en.wikipedia.org/wiki/Kexec
https://github.com/fincham/kexec-remote-debian-install

**Comment by krokodilerian** [comment]
Discussed, basically kexec with an initrd that downoads an image and either untars it or dds it to the sdcard.

**Comment by SuperQ** [comment]
kexec? or [gPXE](http://etherboot.org/)?

**Comment by krokodilerian** [comment]
@SuperQ , can't find any information about this, can I do something from the command line of the box to boot into gPXE?

**Comment by SuperQ** [comment]
I was thinking it may be possible to put something like gPXE in the boot loader, and use that to remotely re-image them.  But, I may be wrong that gPXE is supports the ARM hardware.  I'll have to do some more research.

**Comment by yoe** [comment]
PXE is not supported on ARM hardware, usually. You can boot to a network device if needed, though. I would suggest [NBD](https://github.com/NetworkBlockDevice/nbd), but I'm biased ;-)

**Comment by krokodilerian** [comment]
Created something (tested) in https://github.com/krokodilerian/video-box-reflash, it can be moved to github/fosdem by someone with the proper rights.

Long story short, kexec didn't work, but there's a way to tell uboot to boot something else, and that something else can run dd from a file on the SSD.

**Comment by gerryd** [comment]
Thanks Vasil!

It's now here: https://github.com/FOSDEM/video-box-reflash
