### ISSUE TITLE
di boxes: more needed?

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#115]
We currently have 4 di boxes. Is this enough? Would it help if we provided more?

Possibly related issue: #100

**Comment by krokodilerian** [comment]
Will check with some people how many did we need last year. I think it was mostly in U.

**Comment by krokodilerian** [comment]
According to my checks, only one had been used last time. 4 should be enough, unless ULB has done something weird with their electricity this year.

**Comment by gerryd** [comment]
I think we've used two, one was labelled "U", another one was labelled "H1309". The two other ones are still in their original boxes, so chances are we didn't use those at all indeed.

Closing as the consensus seems to be "no".
