### ISSUE TITLE
test mix panel in K graphics devroom for audio feedback to speaker/devroom manager

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#122]
We don't need a mix panel in the small rooms in upper K, but it might be useful for providing audio feedback to the speaker. Test this for 2018, for potential full rollout in 2019.

Test this with the graphics devroom/Luc.
Speaker microphone -> FOSDEM mix panel---> ULB PA
                                                              \---> camera XLR input

**Comment by krokodilerian** [comment]
We'll skip that to make the setup easier and more manageable.
