### ISSUE TITLE
play with sony pxw-x70

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#123]
This camera seems to combine a lot of the nice things:
* decent sensor and light sensitivity
* builtin 720p streaming over (optional!) wired ethernet
* available at our rental place
* relatively low price

(Bumped into this while reading through the debconf setup documentation at https://debconf-video.alioth.debian.org/ & https://alioth.debian.org/projects/debconf-video/ .

**Comment by yoe** [comment]
The DebConf video team will hold a Sprint the week before FOSDEM at a venue in Diegem. I'm sure we can arrange for one (or more) of their cameras to be available if needs be. We've done this in the past too, with FOSDEM borrowing cameras etc for recording for the 2013 and 2014 editions, at least.

OTOH, I can also fully imagine that it might not be the best time to do this...

**Comment by markvdb** [comment]
Not going into the direct network streaming. No real issues here. Closing.
