### ISSUE TITLE
Background for the standard picture-in-picture video scene

### ISSUE THREAD

**Issue by krokodilerian** [FOSDEM/video#124]
As we had for last year, a background with this year's artwork.

**Comment by veinara** [comment]
![fosdem2018_video_bg5](https://user-images.githubusercontent.com/240089/34916271-3db7f0da-f93e-11e7-98af-d62265d2bad6.png)
![fosdem2018_video_bg6](https://user-images.githubusercontent.com/240089/34916272-3dd5ad5a-f93e-11e7-91b4-b2ccc37e50b7.png)
![fosdem2018_video_bg1](https://user-images.githubusercontent.com/240089/34916273-3df1d958-f93e-11e7-8ae6-746eb7c59f47.png)
![fosdem2018_video_bg2](https://user-images.githubusercontent.com/240089/34916274-3e0e496c-f93e-11e7-8419-e56b602707a6.png)
![fosdem2018_video_bg3](https://user-images.githubusercontent.com/240089/34916275-3e2a90d6-f93e-11e7-8061-63bbd167cd8e.png)
![fosdem2018_video_bg4](https://user-images.githubusercontent.com/240089/34916276-3e462968-f93e-11e7-9d35-5d4aae6d244a.png)

**Comment by veinara** [comment]
![fosdem2018_video_bg7](https://user-images.githubusercontent.com/240089/34916475-9a65cdf4-f941-11e7-923d-e69831ec3577.png)

**Comment by markvdb** [comment]
I like number one the most.

**Comment by gerryd** [comment]
Looks good, thanks! :)

Number one or number five for me.

**Comment by yoe** [comment]
I actually prefer number three. It's less busy (and therefore less distracting)

**Comment by veinara** [comment]
![fosdem2018_video_bg](https://user-images.githubusercontent.com/240089/35553589-3630644a-05a1-11e8-9ac7-f066081c994d.png)

**Comment by krokodilerian** [comment]
committed in infrastructure/
