### ISSUE TITLE
Order strap bags for extra microphone batteries

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#127]
We probably want ~50 pcs of something like https://www.zakken.be/katoenen-tassen/mini-katoenen-zakje-met-koordsluiting-9x13cm-4936?column_kleur=57 with a sufficiently long cord for cleanly strapping the power banks for the microphones to the camera tripod.

**Comment by RichiH** [comment]
If they are meshed, you can see the contents from the outside.

**Comment by RichiH** [comment]
That looks better, yes.

**Comment by gerryd** [comment]
Ordered.
