### ISSUE TITLE
get vga to hdmi adapters

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#128]
* aliexpress, unconfirmed working https://www.aliexpress.com/item/New-High-Quality-Portable-Plug-and-play-VGA-To-HDMI-Output-1080P-HD-Audio-TV-AV/32692452101.html
* https://www.aliexpress.com/item/1080-HD-High-Resolution-VGA-male-TO-HDMI-Female-Converter-Cable-with-Audio-output-Adapter-usb/32945123467.html
* https://www.allekabels.nl/hdmi-omvormer/1792/1376194/vga-naar-hdmi-omvormer.html
* https://www.aliexpress.com/item/2019-HDMI-to-VGA-Digital-To-Analog-Audio-Video-Converter-with-Audio-Adapter-Support-1080P-for/32956670209.html
* https://www.aliexpress.com/item/Full-1080P-black-Mini-VGA-to-HDMI-Converter-With-Audio-VGA2HDMI-1080P-Adapter-Connector-For-Projector/32806428729.html

**Comment by gerryd** [comment]
Ordered a variety of converters. Also added a selection of mini-DP, DP and mini-HDMI to HDMI bits while I was at it.
