### ISSUE TITLE
need access to dhcp settings (network?)

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#13]
If worst comes to worst, we need to be able to replace a box with another one. This means basicly dropping in a mac/ip mapping in the dhcp server and running ansible.

We want to rely on a quick response from the network team for this. Needs coordination with network...

**Comment by RichiH** [comment]
I think you will maintain that file in our repo. That way we can pull it
when you change.

Richard

Sent by mobile; excuse my brevity.

**Comment by gerryd** [comment]
Duplicate of #58
