### ISSUE TITLE
reset Juniper ex2200 password

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#131]
We use this 48 port switch at the core of the video network, for voctops and streamdumper amongst others.

Most probably, this is configured as a dumb switch, but we can't check because the password is unknown. Best to reset it before FOSDEM 2019 to be sure.

**Comment by krokodilerian** [comment]
The user is 'fosdem', and I've forwarded to @gerryd the dump of the config I have.

**Comment by gerryd** [comment]
Yep, fixed.
