### ISSUE TITLE
https://github.com/FOSDEM/video/wiki/hdmi-input-board#Used_A20_pins

### ISSUE THREAD

**Issue by UweBonnes** [FOSDEM/video#135]
Hello (Luc),

comparing the PINOUT in the WIKI and the A20_Bananapi_Schematics.pdf from the sunxi site, VSYNV and HSYNc seem to be swapped. Please recheck!

**Comment by libv** [comment]
Let's go through the motions, and see where the fault lies.

According to A20_Bananapi_Schematic.pdf (a20_banana_pi_v1.4), page 3:
PD26 = LCD0_HSYNC
PD27 = LCD0_VSYNC

According to A20_Bananapi_Schematic.pdf (a20_banana_pi_v1.4), page 9:
LCD0_HSYNC = FPC18
LCD0_VSYNC = FPC16
The logical order is swapped here on the schematic, it seems.

The wiki says:
LCD_29		FPC16		# PD26 == LCD_HSYNC
LCD_30		FPC18		# PD27 == LCD_VSYNC
Which is indeed inverse of what FPC should be.

Good catch. Let me go verify my cable, and swap those wires around, and see whether the display is still happy then.

**Comment by libv** [comment]
Wow. That's some interesting experience for a graphics driver guy. For long i had assumed that these displays did not really care about the length of h/vsync, that they somehow listened to DE more.

The lines were swapped to your findings, and the display is just as happy as before.

Adjusting the wiki to match.

**Comment by libv** [comment]
Again, fantastic catch.
