### ISSUE TITLE
live map of video volunteer locations

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#139]
To be discussed: location tag (video?) volunteers that agree. Potential advantages:
- know who is nearest to what
- no double running to the same point when scrambling at rush hour

**Comment by ShinIce** [comment]
on what kind oy system are you thinking @markvdb ? gps based or something else?

**Comment by krokodilerian** [comment]
This was discsussed around 2022, and that seems to be not-so-useful. The better idea is to leave the per-building teams to sync internally and their per-building-room person to know where they are and see who should go where.
