### ISSUE TITLE
2021 voctomix config

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#148]
Voctomix configuration will need updating:
- ingest q&a output
- play back prerecorded video
- ...

**Comment by yoe** [comment]
FWIW, vogol has UI to start a prerecorded video, and a few other things, so it might be good to look at that before looking at configuration changes.

**Comment by markvdb** [comment]
https://github.com/FOSDEM/infrastructure/blob/master/ansible/playbooks/roles/video-bbb/files/scripts/source-recording.sh is the minimal prototype answer here.
