### ISSUE TITLE
FOSDEM 2021 roomnames in ansible 

### ISSUE THREAD

**Issue by corosuske** [FOSDEM/video#156]
- put the rooms names of the new (virtual) rooms in ansible 
- pull from penta? or ask AGK 
- slugification?

**Comment by corosuske** [comment]
@kergon  can you get me the list of roomnames

**Comment by kergon** [comment]
The room names (=live stream names) are not final.  There will be more.  (And possibly twice this number depending on the decision about how hallway track is to be done.)  There may be additional ones for stands and BOFs.
At the moment they all begin 'V.' for 'Virtual' but that might get changed to classify them if we indeed have new types (D. Devroom, B. BOF, etc.)
The list is published in the xml here - https://fosdem.org/2021/schedule/xml
  <room name="V.lightningtalks"></room>
The complete list can be obtained with this database query - 
  pentabarf=> select conference_room from conference_room where conference_id = 13 and public = true;

**Comment by corosuske** [comment]
we are going to need this soon thou,esp if you are going to double the video rooms the event is only 5 weeks away as of tomorrow 


also doubling the rooms you are doubling the workload on a team that has already indicated that they are overstretched as far as workload is involved. There is no window left to add extra people (mythical man-month)  ... i would highly recoomend against this, also since it would take away the hallway track and just make extra devrooms. just make the hallway track standard matrix chatrooms. it will scale , it is relatively simple , and it does not add extra work for people who have already said they are stretched to breaking point, and that we cant afford to lose at this point

**Comment by markvdb** [comment]
Fixed in ansible. See also https://github.com/FOSDEM/infrastructure/blob/master/ansible/playbooks/roles/video-bbb/files/scripts/list_rooms.py for how we sanitise room names. Had to coordinate with agk because of the fun ways this is all integrated on website and video...
