### ISSUE TITLE
wall clock times: preroll/postroll/interroll

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#169]
@turt2live /TravisR needs to either know or be able to calculate the wall clock time for the start of the q&a if he's to give warnings in every event backstage room.

@kergon @yoe Video length in seconds in penta would be the obvious choice here. @kergon I seem to remember we talked about this and that was also our conclusion...

**Comment by kergon** [comment]
I've set up a database view for the bot to use and can add the video length to it.

**Comment by yoe** [comment]
video length is being pushed to penta nowadays.
