### ISSUE TITLE
sponsors slide

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#172]
@gerryd We need the list of sponsors and their logos for the video loop. Can you get us that?

@krokodilerian 's wife might be able to iron out the visual side.

See also #162

**Comment by gerryd** [comment]
The list of sponsors is not final yet and probably won't be for a little while still. For now, I would suggest you use a placeholder.

Would it be possible to grab the list of sponsors, say, a week before the event and generate the slide? I would say that anything that is in [here](https://github.com/FOSDEM/website/tree/master/sponsors-src) at that point should be included.
