### ISSUE TITLE
extra hd's for vocto servers

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#18]
We need more storage on the 4 vocto machines, to dump the incoming and outgoing streams to. 1 extra Tb in raid 1 per machine should be sufficient.

Bart has 7x 1 Tb 2.5" HDD suitable for the servers. Hopefully we can get those, buy some extra ones.

**Comment by markvdb** [comment]
I will get in touch with B W.

@gerryd , could you get another pair?

**Comment by RichiH** [comment]
Please plan for at least one disco dying on site.

Richard

Sent by mobile; excuse my brevity.

**Comment by markvdb** [comment]
Dumping the 1 Tb disks from the vocto servers. This reduced complexity. We're dumping the streams to a different machine than the voctos anyway...
