### ISSUE TITLE
guide for speakers doing recordings

### ISSUE THREAD

**Issue by ghosty-be** [FOSDEM/video#180]
from AGK on FIT:
https://indiscipline.github.io/post/voice-sound-reference/

**Comment by markvdb** [comment]
Musician here. The device with the best audio and more than acceptable video for webcam use is the Zoom Q8.

**Comment by djnamurlug** [comment]
and : webcam move when speaker touch the laptop or the table.     that could be great if speaker use a remote for change the slides (like kdeconnect)

**Comment by ghosty-be** [comment]
> and : webcam move when speaker touch the laptop or the table. that could be great if speaker use a remote for change the slides (like kdeconnect)

Used LibreOffice Impress Remote on smartphone for giving live presentations...

**Comment by indiscipline** [comment]
> Musician here. The device with the best audio and more than acceptable video for webcam use is the Zoom Q8.

As a happy user of multiple Zoom corp. products I can second that but I have to add Q8 or even Q2n-4k is probably an overkill for a situation of recording a "talking head". Most speakers will be better suited with their existing phones/webcams for video and a good mic+audiointerface for audio. However, Q2n is probably the best device which can act as a plug-and-play webcam in terms of audio quality.

**Comment by markvdb** [comment]
Not relevant anymore for 2024.
