### ISSUE TITLE
speakers formatting text near penta image looks out of place

### ISSUE THREAD

**Issue by modlin** [FOSDEM/video#182]
[instructions/fosdem2021/speakers.md](https://github.com/FOSDEM/video/blob/master/instructions/fosdem2021/speakers.md#talk-video-recordings):

`That is what will be broadcast` is to the right of Penta image but starting only to the image's bottom right.

Usually for languages read line-wise top to bottom, even beside an image, text lines start at the top rather than bottom, unless something else already occupies the top and needs to push text down. But here there isn't anything, making this current bottom-starter line looking a bit out of place.

Screenshot: [Penta image with text off to right bottom](https://pastemyimg.com/view/img6C4475)

**Comment by modlin** [comment]
Possible way to fix is to just not do text wrapping on the side, leave image's side reserved for just white space, and instead have text begin on a new line beneath the image. 

I'll send a pull request for this suggestion.

**Comment by markvdb** [comment]
@modlin thx for your pull request.

Closing because not relevant anymore for 2024.
