### ISSUE TITLE
irc bridging

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#186]
IRC<-> matrix bridging.
- general unauthenticated conference rooms (infodesk, ...). Bridge like last year.
- we had it for each devroom too. Can't seem to find any relevant info who did this/how that happened. Would be really nice to have.

**Comment by ShinIce** [comment]
Bridges are not yet up but will happen soon.

**Comment by ShinIce** [comment]
Infodesk done, rooms will be bridged in the next days.
