### ISSUE TITLE
update chat links on fosdem.org and live.fosdem.org

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#187]
2021:
- main tracks: `https://chat.fosdem.org/#/room/#test:fosdem.org` , `https://matrix.to/#/#test:fosdem.org?web-instance[element.io]=chat.fosdem.org`
- devrooms: `https://chat.fosdem.org/#/room/#ada:fosdem.org` , `https://matrix.to/#/#ada:fosdem.org?web-instance[element.io]=chat.fosdem.org`

2022:
- main tracks: `https://chat.fosdem.org/#/room/#<maintrack>:fosdem.org , https://matrix.to/#/#<maintrack>:fosdem.org?web-instance[element.io]=chat.fosdem.org`
- devrooms: `https://chat.fosdem.org/#/room/#<roomname>-devroom:fosdem.org , https://matrix.to/#/#<roomname>-devroom:fosdem.org?web-instance[element.io]=chat.fosdem.org`

The relevant source code is in <pre>./lib/helpers/schedule_helpers.rb:  def stream_link(track_or_event, is_chat=false)
</pre>

**Comment by kergon** [comment]
main website updated

**Comment by kergon** [comment]
live.fosdem.org either needs another lookup table or some logic to add -devroom to the ones beginning with d and -keynotes to the one starting with k

**Comment by markvdb** [comment]
Source code is https://github.com/FOSDEM/video/tree/master/software/livestream .

**Comment by johanvdw** [comment]
I'm having a look.
