### ISSUE TITLE
matrix: update manuals 

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#189]
Update matrix manuals.

**staff**
Usueful starting points:
- https://github.com/FOSDEM/video/blob/master/instructions/fosdem2021/staff.md
- internal wiki

**speakers**
Useful starting points:
- https://github.com/FOSDEM/video/blob/master/instructions/fosdem2021/speakers.md
- https://fosdem.org/2022/manuals/program/speaker/

**video staff**
Useful starting points:
- https://github.com/FOSDEM/video/blob/master/instructions/fosdem2021/videostaff.md

**Comment by ShinIce** [comment]
- Staff
- - external docu updated https://github.com/FOSDEM/video/blob/master/instructions/fosdem2022/staff.md
- - internal wiki wip right now

- Speakers
- - slightly updated https://github.com/FOSDEM/video/blob/master/instructions/fosdem2022/speakers.md

Did I missed anything @markvdb ?

**Comment by pieterdp** [comment]
For the speakers manual: what to do with https://fosdem.org/2022/manuals/program/speaker/? I think best is to merge them and get rid of one of them.

**Comment by ShinIce** [comment]
Indeed, I think one should be enough.
