### ISSUE TITLE
inconsistencies in presentation_length

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#190]
- example: 12498
  - real duration: 38:54.93
  - presentation_length: 00:00.00
- other similar inconsistencies (all in mozilla devroom): 12496, 12684, 12498, 12595, 12612, 12594, 12597, 12608, 12347, 12547

(as reported by Michael Kohler)

**Comment by markvdb** [comment]
pom:"In open research devroom I edit those fields by hand before video upload phase. They haven't been updated since.
I thought they would be but not so far."

**Comment by markvdb** [comment]
happens in /var/lib/sreview/upload/sync-upload-urls . Can be run separately by hand. Wouter promised to fix this later today.

**Comment by yoe** [comment]
This should now be resolved
