### ISSUE TITLE
12540 12647 12546 13001: 404 on review link

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#192]
pom: the three video which are waiting for review can't be watch in the review link. There is a 404 on those : 12540 12647 12546

**Comment by yoe** [comment]
This is a result of a bug in SReview where sometimes it generates an incorrect ffmpeg command line.

I'll look at this tomorrow.

**Comment by mmuman** [comment]
I have the same error on event 13001 for some days now, after the speaker attempted uploading a too large file, then a small enough that filled up the disk on the server… not sure it's related though.

**Comment by markvdb** [comment]
13094, Multi-language Data Wrangling and Acquisition Conversational Agents, Anton Antonov, D.raku: probably similar issue.

**Comment by markvdb** [comment]
12863, NetOTA - repository protocol for embedded systems, Zygmunt Krynicki, L.lightningtalks

Probably similar issue.

**Comment by rzr** [comment]
from IRC:

<wouter> FYI: videos that were having a 404 are now reinjecting, hopefully this time around it shouldn't happen anymore

**Comment by paulgirard** [comment]
12540 and 12546 are now good and accepted.
12647 is injecting, I will have a look tomorrow.
Thank you!

**Comment by mmuman** [comment]
13001 Is good for me now, thanks!

**Comment by paulgirard** [comment]
12647 is still injecting. it's been something like 12h running now. Looks suspicious isn't it ?

**Comment by paulgirard** [comment]
All good on my side! thank you
