### ISSUE TITLE
sreview: incorrect waiting_for_files states

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#193]
(not urgent)

- i.infodesk: 2 waiting_for_files
- all stands: 1 waiting_for_files. Is this correct?

**Comment by yoe** [comment]
I don't see why not? Some people do more uploads than others.

Is there an actual problem?

**Comment by markvdb** [comment]
Are infodesk actually making videos available through sreview? I have no idea...

**Comment by yoe** [comment]
So, I don't think this is incorrect. If nothing is uploaded, then the state won't change. That makes sense.

I haven't seen anything that would suggest that there is actually a need for a video for the Infodesk.

As such, closing. Feel free to reopen if you have actual proof that a video was uploaded and nothing happened though.
