### ISSUE TITLE
12987: 404

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#195]
- state according to https://upload.video.fosdem.org/overview
Prerecording for talk 'PlayStation 3 Emulation' | Alexandro Sanchez Bach | D.emulator | 2/6/2022, 1:00:00 PM | 2/6/2022, 2:00:00 PM | preview | waiting
- /srv/sreview/upload/injected/d/65/e1d9a1d6824c2f55930fce0e09f8818b1a5cdd175bdd2e408b94c0e5ed85c.mp4 :
  - 1.7 Gb, 2560x1440 resolution
- /srv/sreview/storage/d/65/e1d9a1d6824c2f55930fce0e09f8818b1a5cdd175bdd2e408b94c0e5ed85c/1/main.mkv
  - 0b

**Comment by blackbeard334** [comment]
@yoe @markvdb is there anything I can do to help?

**Comment by blackbeard334** [comment]
The video was reuploaded in 1280 resolution, and seems to be working now

**Comment by blackbeard334** [comment]
I guess downscaling 1440 broke the system 😅

**Comment by markvdb** [comment]
I blessed the review step and sent it off for final acceptance. Closing this one.
