### ISSUE TITLE
prerecorded videos: stuck in uploading scheduled

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#196]
As reported by Nicola Corti, several videos seem to be stuck in the state "uploading scheduled" since several days. Possibly an artefact of the disk space issue or the sreview bugs recently discovered.

Relevant talks:
- 12503, KSP and Plugins. Optimizing Kotlin Multiplatform common code, Anna Zharkova, D.kotlin
- 12643, New features in MariaDB 10.7 and MariaDB 10.8, Ian Gilfillan, D.mariadb
- 12734, MariaDB Optimizer - ongoing development and changes, Michael "Monty" Widenius, D.mariadb
- 12711, MariaDB Galera Cluster and M/S replication, Oli Sennhauser, D.mariadb
- 12710, MariaDB Connection ID, Oli Sennhauser, D.mariadb
- 12455, Introducing Garage, a new storage platform for self-hosted geo-distributed clusters, Alex Auvolat, D.sds
- 13023, Earthstar, Sam Gwilym, D.web3

P.S. Presentation_length is set already.

**Comment by cortinico** [comment]
If that helps:

> 12503, KSP and Plugins. Optimizing Kotlin Multiplatform common code, Anna Zharkova, D.kotlin

This was actually a re-upload, so maybe something happened during one of the subsequent uploads

**Comment by cortinico** [comment]
> 12503, KSP and Plugins. Optimizing Kotlin Multiplatform common code, Anna Zharkova, D.kotlin

This is now in the `done` state. Was it magically solved?

**Comment by yoe** [comment]
No, I fixed it :-)
