### ISSUE TITLE
preview: 404

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#197]
- 12849, Potato Zombies', Scott Wadden, D.nim, current state: preview waiting
- preview actually returning a 404
- 
<pre>
encode-master:/mnt/HC_Volume_16440440/upload/injected/6/8a# ls -l
total 4725476
-rw-r--r-- 1 sreview sreview 2147482575 Jan 30 05:10 07800cfab2089b6655b89c50ff4d4b6d0ea605ba5615bb89ed8db0e59397d.m4v
-rw-r--r-- 1 sreview sreview 1579730519 Jan 30 17:06 07800cfab2089b6655b89c50ff4d4b6d0ea605ba5615bb89ed8db0e59397d.mov
-rw-r--r-- 1 sreview sreview  579642534 Jan 30 23:00 07800cfab2089b6655b89c50ff4d4b6d0ea605ba5615bb89ed8db0e59397d.mp4
-rw------- 1 sreview sreview  532007490 Jan 18 10:43 93555d55343e4ed5050f22ac180e541fc94c12d31c8ab97251cf34c4667c4.mp4
</pre>
Ffprobe tells me:
- The version of the first arriving on the server got corrupted somewhere.
- The second and third ones did get through, but at 1920x1080 resolution instead of 1280x720, possibly triggered a (failed?) transcode.

I've communicated the link to this issue to the submitter.

**Comment by dsrw** [comment]
Thanks for looking at this. I believe the most recent version I uploaded should be in the correct format without transcoding (720p, 25fps, 2Mb/s). Please let me know if I should re-upload, or if there's anything else I can do that might help.

**Comment by markvdb** [comment]
@dsrw Looks like you bumped into an issue that @yoe is still fixing.

No worries. Please keep an eye on the video review link for your talk in penta.fosdem.org . Approve it as soon as you can see the actual normalised video and you should be all set.

**Comment by markvdb** [comment]
Fixed thanks to @yoe . I checked the video and it was ok. Closing.
