### ISSUE TITLE
UPS for vocto machines?

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#20]
Should we get a UPS for the vocto machines or at least some form of redundant power?

**Comment by krokodilerian** [comment]
If possible and if it covers at least parts of the network, then yes.

**Comment by markvdb** [comment]
ups+ proper pdu might be available through Juan. Need to check with him.

**Comment by markvdb** [comment]
Juan has this somewhat older ups
![7391855423114698745 account_id 1 jpg](https://cloud.githubusercontent.com/assets/778760/20382179/fce3fcec-acaa-11e6-9460-7909aaceb6e7.jpeg)

2 pdu's too which we probably have no use for. including for completeness...
![pdu](https://cloud.githubusercontent.com/assets/778760/20382202/1de6205a-acab-11e6-89f8-8c70a1df2de5.jpeg)

**Comment by RichiH** [comment]
Check if the batteries hold a charge and if they do so after a week of
running under load as well. If they blow up during the weekend after years
of no usage...

**Comment by krokodilerian** [comment]
700C is 700VA, which is basically a single server, or not even that, I don't think that would be useful.

**Comment by gerryd** [comment]
This issue is now irrelevant, we are using laptops which come with a built-in UPS.
