### ISSUE TITLE
13192: 404 on preview url

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#201]
The State of Kotlin' | Anton Arhipov | D.kotlin
current state: preview waiting

These are most probably are one and the same issue. Filing separately just to be sure. Closing multiple issues shouldn't be too much of an effort...

**Comment by cortinico** [comment]
I can confirm that this is happening.
Also @martinbonnin experienced the same with 13518. We had to re-upload multiple times in order for the preview to show up correctly.

**Comment by martinbonnin** [comment]
What made the trick was transcoding the video using ffmpeg (the initial video was made with iMovie)

**Comment by markvdb** [comment]
13192 The State of Kotlin' | Anton Arhipov | D.kotlin still needs fixing first.

**Comment by cortinico** [comment]
> still needs fixing first.

What is needed to do? I can see the final review version correctly from Penta 🤔

**Comment by markvdb** [comment]
All fine now. Yay!
