### ISSUE TITLE
Request to manualy delete a duplicated video for stand

### ISSUE THREAD

**Issue by rzr** [FOSDEM/video#202]
Hi,
Maybe this is not the right place for reporting this request,
but I thought it would be easier to track it here.

Those files should be deleted because there are same as video4 :

- https://video.fosdem.org/2022/stands/oniro/stand_video_oniro_video5.mp4
- https://video.fosdem.org/2022/stands/oniro/stand_video_oniro_video5.webm

There are reachable from:

https://video.fosdem.org/2022/stands/oniro/

Thanks

**Comment by rzr** [comment]
Cc: @libv

**Comment by yoe** [comment]
done

Please send the request for the other changes, preferably just to video@f.o
