### ISSUE TITLE
video codec eror on some videos 

### ISSUE THREAD

**Issue by corosuske** [FOSDEM/video#204]
video of talk 12374 did not load prompting an inquiry 
when running thru ffprobe we get 

[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55922eda29c0] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 121 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
 

lookin at other videos, these have the same eror 
12893.mp4    JSON in PostgreSQL - Learning with a case study 
13070.mp4    Hash join in MySQL 8.0

**Comment by krokodilerian** [comment]
Looking into it.

**Comment by markvdb** [comment]
reencoded 13070 right before it started. 12893 still needs similar treatment.

Strangely, ffmpeg 4.3 has a problem with the 13070 file, but 4.4 not.

**Comment by markvdb** [comment]
More undetected:
[12750.mp](http://12750.mp/)4
[12883.mp](http://12883.mp/)4
[13002.mp](http://13002.mp/)4
[12868.mp](http://12868.mp/)4
[12867.mp](http://12867.mp/)4
[12434.mp](http://12434.mp/)4
[12946.mp](http://12946.mp/)4
[12869.mp](http://12869.mp/)4
[12723.mp](http://12723.mp/)4
[12925.mp](http://12925.mp/)4
[13203.mp](http://13203.mp/)4
[12505.mp](http://12505.mp/)4

**Comment by krokodilerian** [comment]
This looks like a problem in colorspace detection. all show as
Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, unknown/bt709/bt709), 1280x720 [SAR 10:9 DAR 160:81], 1418 kb/s, 25 fps, 25 tbr, 16k tbn, 50 tbc (default)

and that unknown part should be bt709. i tried forcing the detection of colorspace, but to no avail. still thinking.

**Comment by markvdb** [comment]
on validate (Debian stable)
ii  ffmpeg         7:4.3.3-0+deb11u1 amd64        Tools for transcoding, streaming and playing of multimedia files
 <pre>ffprobe 13070.mp4 
ffprobe version 4.3.3-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c93b621a00] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 1418 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '13070.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 00:18:49.66, start: 0.000000, bitrate: 1545 kb/s
    Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), none, 1280x720, 1418 kb/s, SAR 10:9 DAR 160:81, 25 fps, 25 tbr, 16k tbn, 32k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 131 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
</pre>

Shortcut: ffmpeg -i brokenfile.mp4 crudelyfixedfile.mp4 works on ffmpeg 4.4, hard fails on 4.3

**Comment by krokodilerian** [comment]
another broken one, 13004

**Comment by markvdb** [comment]
Not reproducible anymore for lack of source files.  New ffmpeg version in Debian stable should fix this anyway.
