### ISSUE TITLE
USB SD card readers for cloning

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#21]
Some USB card readers might be useful for cloning videobox cards using gnome multi writer.

Maybe we should even get plenty of extra SD cards. They're dirt cheap anyway. Would allow us to flash the cards before the boxes are in the same physical place. The saving in time and complexity might really be worth it.

**Comment by RichiH** [comment]
Yes, get extra and prepare them all in advance. Label as well so they all
have a unique ID.

Richard

Sent by mobile; excuse my brevity.

**Comment by markvdb** [comment]
Ordered a month ago by Gerry at techdata, but delivery dates have been shifting continuously...

**Comment by markvdb** [comment]
Not needed anymore. We have everything flashed.
