### ISSUE TITLE
12770.mp4 (dnim-vocto.video.fosdem.org)

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#210]
One talk didn't get through entirely.

One of the "interesting" things is that it seems a 1080p video ended up going through sreview onto the vocto.

Voctomix barfing out on a file it can't handle cpu wise might very well have been a reason.

Wouter, please investigate this in sreview.

**Comment by PMunch** [comment]
The recorded video has the same issue of course, is there a way the pre-recorded complete video could be released instead of the cut one?

**Comment by markvdb** [comment]
Transcoding issue was supposedly fixed in sreview.
