### ISSUE TITLE
2022 archive videos audio problem: codec issue? client library issue?

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#216]
We've received about 4 inquiries about audio issues with the videos for 2022 uploaded to video.fosdem.org .

@yoe Can you dump the exact pipeline with which these were produced? Was this a consistent pipeline between all of them?
@krokodilerian Do you see anything unusual about the files as currently available on video.fosdem.org ?

**Comment by markvdb** [comment]
- MacBook Pro running MacOS 10.15.7, Safari
- Ubuntu 20.04 LTS vlc

**Comment by krokodilerian** [comment]
I'm not sure where I can access all, so tried with two, but there's one very weird thing, all the audio is 96khz (not 48khz or 44.1khz), which might be the issue. Where do we have a copy of all so I can run a script to check?

**Comment by markvdb** [comment]
The faad decoder used by vlc produces audio errors. Grepped from the vlc -vvv output:
<pre>
[00007f1bb4320d40] faad decoder warning: Maximum number of bitstream elements exceeded.
[00007f1bb4320d40] faad decoder warning: Maximum number of scalefactor bands exceeded.
[00007f1bb4320d40] faad decoder warning: Array index out of range
[00007f1bb4320d40] faad decoder warning: Bitstream value not allowed by specification
[00007f1bb4320d40] faad decoder warning: Channel coupling not yet implemented
</pre>

**Comment by markvdb** [comment]
According to @yoe , some useful info on the exact scripts run that yield this is to be found in review.v.f.o:~sreview/script-output/{cut,trn}* .

**Comment by yoe** [comment]
This was very much a non-actionable issue (vague descriptions that I couldn't do anything with), and it's about last year's stuff, so not much we can do about this anymore.

Closing.
