### ISSUE TITLE
spam because of missing dkim/spf info

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#217]
from #speakers:chat.fosdem.org

I see it was just released, did you get the mail this time?

I did. Turns out it got flagged as spam. Sorry for the inconvenience :/

Huh. Upon closer insepction, a whole number of mails got flagged that way. Looks like they had not been signed with DKIM and our mailserver could not find any SPF information. Very odd. And slightly unsettling.

yes, these were the videos sent out as part of the video review system
I'll file a bug to make sure that this is prevented for next year
(this was an issue in the past too)

**Comment by yoe** [comment]
Mails are now sent through the official fosdem.org mail server, so this should not be an issue anymore; closing.
