### ISSUE TITLE
Chinese usb stick raw video uvc device

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#218]
We want to check if we can replace a box with the Chinese raw hdmi usb stick.

This ffmpeg pipeline picks up audio and video from one of our new Chinese usb sticks:

<pre>
ffmpeg -y -nostdin -init_hw_device vaapi=intel:/dev/dri/renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device intel -filter_hw_device intel  \
	-probesize 10M \
	-analyzeduration 10M \
         -f alsa \
         -i hw:2,0 \
         -f video4linux2 \
         -video_size 1280x720 \
        -itsoffset 00:00:00.450 \
	-i /dev/video3 \
	-threads:0 0 \
	-aspect 16:9 \
	-filter_complex "[0:a]channelsplit=channel_layout=stereo[left][right]; [1:v] format=nv12,hwupload [vout]" \
	-map '[vout]' \
	-c:v:0 h264_vaapi \
	-g 45 \
	-maxrate:v:0 2000k -bufsize:v:0 8192k \
	-b:v:0 1000k \
	-qmin:v:0 1 \
	\
	-map '[left]:1' \
	-ac 1 -strict -2 -c:a aac -b:a 128k -ar 48000 \
	-map '[right]:2' \
	-ac 1 -strict -2 -c:a aac -b:a 128k -ar 48000 \
	-y -f mpegts - | test.ts
</pre>

**Comment by gerryd** [comment]
Have a look at https://github.com/BertoldVdb/ms-tools
Support for the MS2130 has been added just hours ago: [9ef466e](https://github.com/BertoldVdb/ms-tools/commit/9ef466edf9751d7bdb6ccb0711ce368565c00eb1)

**Comment by markvdb** [comment]
Developing a new FOSDEM box based on these.
