### ISSUE TITLE
vocto boxes: clear old ILO settings

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#22]
Clear the old ILO settings from the vocto boxes. Coordinate with server@/network@ if we need settings of our own.

**Comment by RichiH** [comment]
Yes, they should all have the same credentials.

Do we need Java or something to connect?

Will there be one tested machine which has Java or whatever installed in
NOC?

Can we monitor ILO? How? Prometheus?

How do we firewall/VPN them off?

Richard

Sent by mobile; excuse my brevity.

**Comment by gerryd** [comment]
This issue is irrelevant as we ditched the HP servers.
