### ISSUE TITLE
feeding high fps to the capture device b0rks it

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#227]
- does not recover through any of:
  -  reverting to known good fps
  - usb resetting the capture device
  - restarting the resolution detection

**Comment by markvdb** [comment]
Resetting the laptop's usb port that the capture box is connected to works.

**Comment by krokodilerian** [comment]
fixed by finding either the device or the port in /sys/bus/usb, and doing `echo 0 > authorized; sleep 1; echo 1 > authorized`

**Comment by markvdb** [comment]
We've been able to reproduce this as follows:
- Switch everything off.
- Connect the capture device hdmi out to a hdmi out device.
- Switch both capture device and hdmi out device on.
- Connect a hdmi input device to the capture device hdmi in.
- The hdmi input device will now probably see the capture device name (HJW 27") and some ridiculously high fps'es as were originally advertised by (TODO which device>).
- Set or auto set a high fps device.
- You now have a b0rked capture device with a functioning hdmi loopout.

**Comment by markvdb** [comment]
- We've found the EDID information in the device's FLASH and RAM.
- We've gotten it out through hdmi and confirmed these are all three identical.
- We've modified the edid to lower the max vertical refresh rate from 144 to a sane 60.
- We've verified that naively copying this modified edid to RAM does not work.

**Comment by markvdb** [comment]
Our in-house professional go programmer has found a way to recalculate the firmware checksum. We've successfully replaced the EDID info, cut the high refresh rates from it, and more. This should now be a non-issue.
