### ISSUE TITLE
mainline linux cheap h264 capable sbc's

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#228]
Couldn't sleep. Unable to do any brain intensive work. Able to do some scrolling for low power h264 encoding sbc's.

- Some Intel Atom chips support QuickSync/VA-API hw accelleration with minimal tdp: https://ark.intel.com/content/www/us/en/ark/search/featurefilter.html?productType=873&0_QuickSyncVideo=True&1_Filter-Family=29035
- On armhf, the Rockchip family might be of interest:
  - several support mainline h264 encoding
  - some RK3588 based boards feature hdmi input, audio and resolution detection. Apparently all BSP packages for now, but mainline supposedly coming up. Interesting boards are costly though:
    - Firefly core 3588J ($209)
    - Radxa rock 5b (130.95 GBP excl. VAT)
    - BPI-W3 ($162 @ aliexpress)
    - Pine QuartzPro64 ($150 devboard, $300? user board)

**Comment by RichiH** [comment]
I was under the impression that Raspi 4 can do H.264 up to FHD in hardware?

**Comment by ghosty-be** [comment]
looks like it, according to this:
https://www.hackster.io/news/chris-griffith-puts-the-raspberry-pi-s-hardware-h-264-encoder-through-its-paces-1d804e538d9e

**Comment by libv** [comment]
Allwinner A20 does H.264, and there should be a ton of BPIs available already, and there is open source code available. It just needs to be tied into the likes of ffmpeg or gstreamer.

**Comment by libv** [comment]
RPi is seriously non-free hardware.

**Comment by markvdb** [comment]
Forgot to mention it also needs to reliably speak usb3.

**Comment by libv** [comment]
Go with intel hw. Everything else will need man-months of kernel and driver work. If you want to go with RPI and their blobbed RTOS based hardware, you can just as well have intel microcode and/or UEFI BIOS.

**Comment by markvdb** [comment]
Planning to experiment with https://www.aaeon.com/en/p/up-developer-board-intel-apollo-lake-up-4000 (with low profile heat sink).

**Comment by krokodilerian** [comment]
We're going with the radxa x2l, which seems to work and I think we can close this one.
