### ISSUE TITLE
vocto boxes hardware test

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#23]
The vocto boxes are relatively old. We want to test them for any possible hardware issues before putting our crucial video systems onto them.

Cpu burn tests, memory tests, ... What else?

**Comment by RichiH** [comment]
CPUburn
Badblocks -swo
Memtest

Label all machines, document all test results in git.

I have a basic script which does party PS this. Is there better?

Richard

Sent by mobile; excuse my brevity.
