### ISSUE TITLE
video boxes hardware testing and inventory.

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#24]
The video boxes from nl have come back untested. We need them all thoroughly tested. This probably goes hand with flashing SD cards.

Need to reinventory the cables and adapters that come with every box. This _will_ require reordering some of these materials because some obviously got lost last year. A clean inventory sheet might 

They are stored in J's attic, but they can't be tested around there.  Moving them in the flight cases is safest. (Mini)van required to move them all though.

Where can we test them then?
Can we temporarily store them somewhere near the testing site?

**Comment by RichiH** [comment]
Same test scripts and labeling system so we have one global procedure?

We should do proper FQDN.

Richard

Sent by mobile; excuse my brevity.

**Comment by markvdb** [comment]
Existing video boxes tested, labeled except for:
* ~5 from Jan's place
* 1 new spare from Riga
* 2 from .bg
