### ISSUE TITLE
get video boxes from .lv and .bg back

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#25]
* 8 boxes in .lv (6 of which are new).
* ?4 boxes in .bg
These should come back fully tested, our standard bananian image preinstalled. We expect them to be without any cables, and should account for that in our cables and adapters order!

When do we need them back in Brussels? Where do we ship them?

**Comment by krokodilerian** [comment]
I have  2 boxes in .bg.

**Comment by RichiH** [comment]
We need to test them after transport.

Richard

Sent by mobile; excuse my brevity.

**Comment by markvdb** [comment]
Boxes from .lv back, tested, labeled and flashed with the new image.
