### ISSUE TITLE
Will an unavailable network uplink kill the dump to ssd?

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#26]
Make sure this does not happen because of some strange reaction with ffmpeg -f tee ...

**Comment by markvdb** [comment]
See https://github.com/FOSDEM/video/blob/master/software/ansible/playbooks/roles/videobox/templates/bmd-streamer/bmd-streamer.sh

**Comment by krokodilerian** [comment]
If ffmpeg pushes to UDP, no network issue will break it, whatever the situation, as UDP is stateless enough. The dump can be done by using -f tee on ffpmeg, there's an example in the video wiki and I will update the script.

**Comment by krokodilerian** [comment]
I stand corrected, if there's no route when ffmpeg starts, it will bomb out with 
av_interleaved_write_frame(): Network is unreachable
I will need to think of a solution, if this is an expected case.

**Comment by markvdb** [comment]
< krokodilerian> the only option i can think of is bmd-streamer -> ffmpeg to both loopback udp and recording, and another ffmpeg from
                          loopback udp to multicast

**Comment by krokodilerian** [comment]
Done in the following way:
bmd-streamer | ffmpeg -f tee to two mpegts over udp streams, both on localhost on ports 4000 and 4001. A service video-streamer pulls 4000 and sends it to the multicast, a service video-recorder records it. The recorder is disabled by default.
(also, the status display show if recording is enabled or not).

Remaining issue is how to start the recording when there was no network whatsoever (e.g. we couldn't login into the box and enable it). Maybe cron?

**Comment by markvdb** [comment]
Not an issue anymore.
