### ISSUE TITLE
Communication with speakers and devroom managers

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#28]
In 2016, communication with speakers and devroom managers wrt video was chaotic, to put it mildly. What needs to happen to improve that?

**Comment by krokodilerian** [comment]
* Instruction leaflets and email for devroom managers with:
	* pre-talk configs/checks (is there a camera, is it pointed where it needs)
	* how important is to have a mic on the speaker
	* how to connect the speaker and see that everything is ok
	* how to access/use the video mixer controls (optional)
	* how to report problems (#fosdem-video, close people from the team)
	* how to log talk beginning/end

* Email to all speakers + a leaflet or something
	* VGA or HDMI or bring your own converter
	* wear mike
	* you WILL BE RECORDED and released under this specific license (CC-sth?)

It'd be very nice if we can get all devroom managers and give them 20-30 minute talk on all this on Friday, but that doesn't seem possible.

**Comment by markvdb** [comment]
It can happen on Saturday morning I guess if we have enough manpower. We now have spare sample sets of mostly everything to give a live demo with a spare...

M

**Comment by krokodilerian** [comment]
Is it possible to do this in the evening somewhere in K? Saturday morning will be busier...

**Comment by markvdb** [comment]
We can try I guess to get as many devroom manager people to come over to the campus on Friday evening...

**Comment by kergon** [comment]
1) Info emailed at least a week in advance, preferably two weeks
2) a training video to watch showing the system in operation
3) a test system that allows people to use the software and become familiar with it at their leisure before they travel
4) A demonstration/hands on session in one devroom per building at 9.30am Saturday morning.

**Comment by krokodilerian** [comment]
https://github.com/FOSDEM/video/blob/master/instructions/sources/FOSDEM_Devroom_manual.md

Please comment. Also, how do these get printed? I can generate PDFs with the user/pass in there.

**Comment by markvdb** [comment]
Fairly good document by krokodilerian. Closing.

**Comment by yoe** [comment]
I notice the "Review" section of the documentation says "expect email with username and password". This is not correct; devroom managers are simply CC'd on the "please review your talk" mails that are sent to speakers.

**Comment by krokodilerian** [comment]
@yoe  I just pushed 3ed7c6fd03e31624cf8819eb57b1ba272959d972 which should be right, can you take a look?

**Comment by yoe** [comment]
@krokodilerian that looks great, thanks
