### ISSUE TITLE
Get cheap bare metal machines for streaming/pseudocutting/postprocessing

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#31]
scaleway.com.

* Reserve ip addresses.
* Check limitations in terms of ip's, devices.. For example: docs say 50 ip reservations max, practice points out only 10.
* When do we want to have these all up?

**Comment by gerryd** [comment]
I have had a chat with their support team, our account limitations at Scaleway are as follows:

- IP addresses: 100
- C2L: 20
- C2M: 25
- C2S: 25

We can also launch a bunch of virtual machines if need be. They do ask that we deploy to Amsterdam if we intend to launch a large number of instances, as they have way more capacity there.

I'd say all production instances should be up and running the week before the conference.

**Comment by krokodilerian** [comment]
@gerryd , stupid question, but what are C2L, C2M and C2S?:)

**Comment by gerryd** [comment]
@krokodilerian see https://www.scaleway.com/pricing/#pricing_baremetal

- C2S is the €11.99/month one
- C2M is the €17.99/month one
- C2L is the €23.99/month one

The €2.99 server is not usable since they don't offer IPv6 on that one at all.
