### ISSUE TITLE
sync to video.fosdem.org and potentially other consumers

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#33]
Sync from whatever does the cutting to video.fosdem.org needs to be configured.

What about youtube. Do we want to be on youtube? Needs discussion.

**Comment by krokodilerian** [comment]
Sync from sreview is happening. Do we want youtube, in the end, who has to decide?

**Comment by RichiH** [comment]
On Tue, Feb 7, 2017 at 3:41 PM, Vasil Kolev <notifications@github.com> wrote:

> Do we want youtube, in the end, who has to decide?

To reach most people, and as others will upload this anyway, we should
do clean batch uploads of all our content, imo.


Richard

**Comment by markvdb** [comment]
We want to do uploads youtube. This means using the metadata from penta.

https://anonscm.debian.org/cgit/debconf-video/youtube.git/tree/README might give some inspiration.

**Comment by markvdb** [comment]
If we want to be able to programmatically upload mp4 content to youtube, we probably have to embed some metadata into the mp4. See http://atomicparsley.sourceforge.net for inspiration on how to do that.

**Comment by yoe** [comment]
I've been talking to Stefano, who wrote the YouTube import stuff for DebConf. It is *absolutely* the intention to integrate this into SReview.

**Comment by markvdb** [comment]
Wouter,

Could we have an update here on how this happens now between sreview and youtube?

Thank you!

Mark

**Comment by markvdb** [comment]
Never mind. I perfectly remember it just works, for some value of just working. Closing this issue.

**Comment by yoe** [comment]
On Sat, Dec 01, 2018 at 10:17:43AM -0800, Mark Van den Borre wrote:
> Never mind. I perfectly remember it just works, for some value of just working.
> Closing this issue.

Yeah, we dump some output metadata files that then get reprocessed by the
YouTube uploader. It works, kinda, but sometimes we generate duplicates. Want
to talk to Stefano about fixing that, but Not Yet(tm)

-- 
To the thief who stole my anti-depressants: I hope you're happy

  -- seen somewhere on the Internet on a photo of a billboard
