### ISSUE TITLE
contacts with YR (ULB)

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#38]
For audio and beamers, we need to be in touch with YR from ULB.

Who is going to do this: Wouter S or Mark V? Mark V did it last year, Wouter S would like to make sure that better coordination with network cabling happens...

**Comment by corosuske** [comment]
Im willing to do this .... can i find Contact details on the fit wiki?
Anything i should know before contactibg them ?

**Comment by markvdb** [comment]
Wouter, I did this last year. If we could go there together, we might give him a feeling of continuity. What do you think?

Vasil,  we had these ground lift devices at VUB/SOTM. Are these also useful/needed at FOSDEM?

**Comment by corosuske** [comment]
sounds perfect :+1: when would you want to do this ?

**Comment by markvdb** [comment]
Had a productive meeting with Renard. Everything ok there. Following up on some minor technical details next week.
