### ISSUE TITLE
streaming server deployment

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#4]
A minimalist nginx rtmp streaming server setup, properly deployable. Debian stable based.

Gerry suggested one machine per room. Technically overkill, but dirt cheap since and makes sense since:
- we only need them for a week or so
- 100% guaranteed to scale
- reencoding to webm/vp9 benefits from a lot of cpu
- the videos already available
- room.stream.fosdem.org host naming scheme simplifies integration and postprocessing

**Comment by krokodilerian** [comment]
Main issue: these need to have enough bandwidth to support the number of users. 1gbps can support ~900 users (1mbps streams, overhead of IP and audio, yadda, yadda, yadda), which might not be enough for the main rooms.

Configs are in the making.

**Comment by markvdb** [comment]
https://github.com/arut/nginx-rtmp-module/issues/668 might help distribute the load

**Comment by markvdb** [comment]
10:14:04 < krokodilerian> well...
10:14:19 < krokodilerian> my idea was one ingest node (or two), e.g. backend
10:14:33 < krokodilerian> and fuck-knows-how-many fronts that cache segments
10:14:43 < krokodilerian> and the fronts are load-balanced via dns
10:14:53 < krokodilerian> and the dns records have ttl of 60s

**Comment by markvdb** [comment]
https://github.com/Viblast/hls-proxy
https://github.com/arut/nginx-rtmp-module/issues/668

**Comment by markvdb** [comment]
Streaming backends are in ansible now thanks to Gerry ( /me was watching across his shoulder). Worked around cross origin resource sharing limitations for HLS.

Frontend machines were set up (not in ansible yet though!).

First tests with hls-proxy done on the frontends. Functionally ok. Requires thorough testing for stability still.

**Comment by markvdb** [comment]
Alternative edge/frontend implementations using only nginx itself.

https://groups.google.com/forum/#!topic/nginx-rtmp/rx_54CBKv8Y
https://github.com/arut/nginx-rtmp-module/issues/668

Need to also understand the builtin commands in nginx-rtmp. There may be something nice in there too...

**Comment by markvdb** [comment]
Streaming stack set up.
