### ISSUE TITLE
Replace Bananian with pure Debian

### ISSUE THREAD

**Issue by gerryd** [FOSDEM/video#41]
I'd like to see if we can replace Bananian Linux with a pure Debian install. Shouldn't be too hard. Low prio for now, Bananian works well enough.

**Comment by johanvdw** [comment]
This shouldn't be hard - I have a banana pi at home running pure debian. I had to use the stretch installer to have hdmi output during the install.
https://wiki.debian.org/InstallingDebianOn/Allwinner

**Comment by krokodilerian** [comment]
@gerryd , what's the reason for it? What would you benefit if it's pure debian? AFAIK, if bananian is supported and is tailored for the board, it should work better and in turn be better for us (and it'll be able to use the same set of packages + some more from bananian themselves, AFAIK).

**Comment by RichiH** [comment]
Pro: native packages, no config magic.
Con: No optimization in compile flags

Richard

Sent by mobile; excuse my brevity.

**Comment by RichiH** [comment]
Further pro: we can put in a laptop and be sure it is a full replacement.

Richard

Sent by mobile; excuse my brevity.

**Comment by johanvdw** [comment]
Kernel sources for bananian are not available. So you don't know what your run + you can not create modules.
+ you can rely on debian for security updates for the whole system

**Comment by markvdb** [comment]
See also #2

**Comment by markvdb** [comment]
Done. Running standard Debian now and mainline kernel.
