### ISSUE TITLE
Grafana diagram for video overview

### ISSUE THREAD

**Issue by RichiH** [FOSDEM/video#42]
If we had a diagram which shows video boxes in rooms in buildings, any physical cuts could be diagnosed much quicker. Please see https://github.com/jdbranham/grafana-diagram

**Comment by markvdb** [comment]
Ping. Any progress on this?

**Comment by krokodilerian** [comment]
I really want this for 2018 :) We had bits of it in some way, but nothing I can show on a screen (and no screen, but there should be a separate one for it next year).

**Comment by RichiH** [comment]
Sorry, I totally forgot about this :/

I did create the network graph though; have a look at that.

**Comment by RichiH** [comment]
https://dashboard.fosdem.org/dashboard/db/ulb-switching-overview

**Comment by markvdb** [comment]
Can we please have an updated overview of the network graph? Would be very useful for Vasil.

**Comment by markvdb** [comment]
Closing as the current thing is good enough for video@.

@RichiH , feel free to reopen on general infra if you would like to.
