### ISSUE TITLE
Send links/screenshots of diagrams to @jdbranham 

### ISSUE THREAD

**Issue by RichiH** [FOSDEM/video#43]
As per https://github.com/jdbranham/grafana-diagram/issues/29 , once we have something to show from https://github.com/FOSDEM/video/issues/42 , we should show @jdbranham .

**Comment by jdbranham** [comment]
Thanks @RichiH !!

**Comment by markvdb** [comment]
Mermaidised graph from graphviz. Still somewhat in flux, so not every single bit of info is in there, but gives you a fairly accurate idea at least.

https://github.com/FOSDEM/video/blob/master/graph/web.html

**Comment by markvdb** [comment]
Richard, as you asked me to port this diagram to mermaid, can you make sure it becomes readable?

**Comment by markvdb** [comment]
Ping. Any progress on this?

**Comment by RichiH** [comment]
Can do that once @corosuske was at ULB.

**Comment by RichiH** [comment]
Found it on public.
