### ISSUE TITLE
Dependency on jsdelivr.net

### ISSUE THREAD

**Issue by SWATx** [FOSDEM/video#52]
Thanks to the noscript Firefox plugin, I noticed that when loading the player I need to allow jsdelivr.net, since certain javascripts are included from there. It would be easier (just allow our domain in noscript) and more robust (what if their site is down or gets hacked) if this dependency would be removed.

**Comment by RichiH** [comment]
We should self host that, yes.

Richard

Sent by mobile; excuse my brevity.

**Comment by gerryd** [comment]
That was the idea, indeed, no worries, I'm probably just as paranoid as you are ;). This is just a copy & paste of their example.

**Comment by gerryd** [comment]
Done.
