### ISSUE TITLE
get 200 AA batteries for audio system

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#55]
4 sets * 4 batteries * 12 rooms= 192 batteries

https://www.amazon.de/Varta-Batterien-Vorratspack-umweltschonender-Verpackung/dp/B00LN803LE/ref=sr_1_1?ie=UTF8&qid=1480444532&sr=8-1&keywords=aa%2Bbatterien&th=1 for example

**Comment by gerryd** [comment]
Done.
