### ISSUE TITLE
video vlan dhcp leases only for known mac addresses

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#58]
It would be good to limit the leases the dhcp server on the video vlan distributes to known MAC addresses:
* video boxes
* vocto laptops
* video team laptops
* monitoring machines

I will make sure to collect the relevant MAC addresses for the video team people in time.

**Comment by krokodilerian** [comment]
voctohost0 00:23:7d:d3:6a:e8 ilo 00:23:7d:d3:6a:ec
voctohost2 18:a9:05:57:af:22 ilo 18:a9:05:57:af:26
voctohost5 18:a9:05:55:e9:88 ilo 18:a9:05:55:e9:8c
voctohost4 00:25:b3:d7:c2:5e ilo 00:25:b3:d7:c2:62

**Comment by krokodilerian** [comment]
Vasil's laptop: 00:21:cc:b3:80:63 (wired)

**Comment by markvdb** [comment]
Mark's laptop: f0:de:f1:c4:7a:b4

**Comment by gerryd** [comment]
@RichiH any news? You mentioned in #13 that there would be a file somewhere which the video team could edit. I think most (all?) MAC addresses have been documented now, so we'd like to get that done Real Soon Now (tm).

**Comment by RichiH** [comment]
Do we have a list of all devices, already?

**Comment by gerryd** [comment]
All but 6: https://github.com/FOSDEM/video/tree/master/software

I will add one in a few minutes (once the SD card has been flashed), @markvdb has the remaining 5 boxes.

**Comment by krokodilerian** [comment]
It was better without this limitation, I suggest we have leases for the boxes/voctops only for 2018.
