### ISSUE TITLE
split up dump directories per room

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#59]
The stream dumps on the streaming backends should be split up by room. This will keep some overview. Otherwise, this might be lost. Especially in case of frequent interruptions, the number of files might grow very quickly...

**Comment by markvdb** [comment]
https://github.com/FOSDEM/video/blob/master/software/ansible/playbooks/roles/streamer-backend/templates/nginx/nginx-rtmp.conf

**Comment by krokodilerian** [comment]
To do this, all we need is the record_suffix to start with / and to have all the stream names as subdirectories in the record directory.
