### ISSUE TITLE
monitoring screen

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#6]
The thumbnails can probably be reused for the monitoring screen too... Or even better would be to have real streams with mutable audio...

Something like this maybe (comments welcome!):
![stream_monitoring_screen](https://cloud.githubusercontent.com/assets/778760/19781706/ca6381c8-9c8a-11e6-8184-91b9be38069c.png)

**Comment by RichiH** [comment]
Sound meters for left/right channel below the video so we can see if there's audio

**Comment by krokodilerian** [comment]
I still have no way of getting audio levels in the thumbs, need to think of something, as audio requires longer listening to actually get something (e.g. i need to parse 5-10sec of stream to get the peak level to display). I was thinking about something that continuously parses all audio streams and keeps somewhere a JSON of the peak/avg for the last 10s, but I don't know how feasible it is and how long would it take to implement.
(overlaying on top of the thumb should be easy)
note, there needs to be a way to distinguish stale data, both for the audio meter and for the thumb, so we're not stuck with a hung stream.

**Comment by markvdb** [comment]
Vasil, you were really interested in https://github.com/voc/multiview-monitor . Adding it here for your convenience.

**Comment by krokodilerian** [comment]
Adding here a suggestion from a friend, mpv can use a lot of hardware accelerations and it might be possible to play a lot of streams with it: https://github.com/int3l/fostest/commit/032b3542751c7664bfe20c8f68d049c9bf85b0f1
