### ISSUE TITLE
Use nginx-rtmp notify module hooks to help (human) monitoring

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#60]
https://github.com/arut/nginx-rtmp-module/wiki/Directives#notify

We want to know things like when a certain app or recorder stops recording for example...

**Comment by SuperQ** [comment]
It looks like this calls URLs for various state changes.  We don't really have a good mechanism for handling that.  It's possible we could setup a simple webserver with instrumentation for various URLs.

**Comment by markvdb** [comment]
We discussed this. An irc bot would probably be best. Wishlist, low priority.

**Comment by krokodilerian** [comment]
Moving to vlc, irrelevant now.
