### ISSUE TITLE
Switches for the voctops

### ISSUE THREAD

**Issue by krokodilerian** [FOSDEM/video#63]
We need two 24-port gigabit switches for the encoders.

**Comment by markvdb** [comment]
Note that a 48 port switch for flashing is a totally different thing. We need these 2 24 port switches for the voctops...

**Comment by corosuske** [comment]
would one 48 port swicth work as well ??? or do you really need 2 switches ??

**Comment by krokodilerian** [comment]
@corosuske, when we did the calculation, we need two sets of shelves to put all the laptops, and if we go with one switch, we'll need cables that are too long (more than 5m).

**Comment by corosuske** [comment]
why is 5M too long ??? i have similar shelves here and if the switch is well placed 2 M should be more than enough

**Comment by krokodilerian** [comment]
5m is too long because the normal patch cables coming from the factory are up to 5m. For the other thing, with all the placements and calculations we did two switches seemed like the better idea, and there are a lot of other cables to be taken into account for all this.

Are two switches a problem? If so, I can see if I can bring some.

**Comment by gerryd** [comment]
Wouter should have some switches, Vasil will bring some more as well. Plenty of switches for everyone! :)

Closing.
