### ISSUE TITLE
Misc equipment for the voctops

### ISSUE THREAD

**Issue by krokodilerian** [FOSDEM/video#64]
- [x] IKEA shelves 2 x OMAR 698.290.83
- [x] 5 x powerstrips (10 sockets each)
- [x] plenty of network cables, 3m and 5m
- [x] velcro strap rolls (like https://www.amazon.com/VELCRO-Brand-ONE-WRAP-Double-Sided-Multi-Purpose/dp/B000078CUB )

**Comment by gerryd** [comment]
These have all been ordered.
