### ISSUE TITLE
rtmp stream from udp sink on voctops

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#66]
There is a problem with casting an rtmp stream from the live mixed udp sink on the voctops. Ffmpeg isn't able to detect the video resolution in the udp stream, so it barfs out.

The reason seems to be the ffmpeg version from deb-multimedia.org (2.6.9) installed on these. It is prehistoric.  Debian (proper) backports has 3.2.2. The problem does not manifest itself there.

If I understand correctly, we do depend to some extent on deb-multimedia.org packages because that is what some voctomix bits are built against on Debian stable. https://github.com/voc/voctomix#installation-on-jessie Their repo is https://c3voc.de/voctomix/dists/jessie/non-free/binary-amd64/ . Quite a lot of bits it seems, so murky waters...

On top of that, the deb-multimedia.org packages may be ancient, but they are compiled with libfdk_aac , which we rather want for audio encoding (less cpu, higher quality).

What do we do with this? Here's a few of the options:

1. Use our own ffmpeg package. Rebuild ffmpeg 3.2.2 from debian-backports with libfdk_aac support compiled in?
2. Keep ffmpeg 2.6.9 from d-m.o on the voctops. Stream from elsewhere (the dumpers?). Hmm, single point of failure, what could possibly go wrong?
3. Check if ffmpeg 2.8.9 from d-m.o backports solves the streaming issue? Really not a fan of than one either, as it would keep us with an ancient ffmpeg and also require retesting the voctomix setup...
4. ?

**Comment by markvdb** [comment]
testing with `apt-get install ffmpeg=7:3.2-2~bpo8+2` on an installed voctop

**Comment by krokodilerian** [comment]
For your last comment, you mean that even with a good ffmpeg version you're unable to receive the multicast from the same machine that originates it and have the right resolution, etc? Did you try adding -analyzeduration and -probesize?

We can probably force the input resolution for this, worst-case (we have it in the config).

**Comment by markvdb** [comment]
No, with the "good" ffmpeg, I can streamcast to the rtmp server from the vocto udp multicast sink. The problem is that this sink seems to be garbled. Which may have something to do with the gstreamer packages from c3 we use being compiled against largely different ffmpeg versions or not.

What I have tested I _can_ do is listen to the voctop sink udp multicast on my laptop, and stream it to the rtmp server from there using this same recent ffmpeg (3.2).

**Comment by krokodilerian** [comment]
If by "garbled" you mean there's no video in it, the anaylzeduration stuff should be able to fix it. If it's something else, then it's weird, because this is what the sources use - they read the UDP stream and decode it...

**Comment by markvdb** [comment]
fixed in ded681c
