### ISSUE TITLE
audio normalisation: (where) do we want it?

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#67]
We probably want audio normalisation. Wouter has a good point there.

The most logical spot to have it might be at the level of https://github.com/FOSDEM/video/blob/master/software/ansible/playbooks/roles/streamer-backend/templates/nginx/nginx-rtmp.conf#L26 or review.

Needs discussion.

**Comment by krokodilerian** [comment]
@yoe , you added that in sreview, right?

**Comment by yoe** [comment]
On Tue, Feb 07, 2017 at 06:38:54AM -0800, Vasil Kolev wrote:
> @yoe , you added that in sreview, right?

Yes, SReview runs bs1770gain over all the released talks.

-- 
< ron> I mean, the main *practical* problem with C++, is there's like a dozen
       people in the world who think they really understand all of its rules,
       and pretty much all of them are just lying to themselves too.
 -- #debian-devel, OFTC, 2016-02-12
