### ISSUE TITLE
install detect_files on streambackend servers

### ISSUE THREAD

**Issue by yoe** [FOSDEM/video#68]
For sreview to know that there's new content, a script needs to be run on the streambackend servers. This is the `detect_files` script in the sreview repository.

The script also needs a configuration file. I have created a minimal version that contains just the things needed for the detect_files script; it's also in the sreview repository as "scripts/config.pl-detect_files". Note that there's one line which ansible would need to update (it's marked with a comment).

The script would need to be run from cron, a few times per hour (how often exactly depends on what the average run time is; we'd have to test a few times to figure that out). Alternatively, I could have it loop and wait in between loops; if we go down that route, it would have to be set up to started at boot time, and then I'll just make it wait 10 minutes or so between every loop.

**Comment by krokodilerian** [comment]
Was installed and ran normally.
