### ISSUE TITLE
live.fosdem.org web overview code

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#69]
Needs checking in, plus...

The webapps:
<pre>
ll['title'] = 'Live video stream from the room'.
ll['url'] = 'https://live.fosdem.org/watch.php?room=' << e['room']
</pre>
During the event, the xml on each talk includes a link, 20mins before until 20mins after.
So this even appears in those web apps people use. It's an issue when the live URLs change, as they are hardcoded.

Best to be aware of that when updating the live streaming overview page.

Agk has been updating fosdem.org to fit with the new room url scheme à la https://live.fosdem.org/watch/aw1121 .

**Comment by kergon** [comment]
URL changed to the new ones - room name with suffix stripped
ll['url'] = 'https://live.fosdem.org/watch/' << e['room'].gsub(/_.*/,'')

**Comment by gerryd** [comment]
All done.
