### ISSUE TITLE
courier quote for camera delivery

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#71]
We probably want a courier quote for camera delivery, as an alternative to two staff renting and driving across the Netherlands.

Vasil and I seem to remember that this was being planned...?

**Comment by markvdb** [comment]
2018

**Comment by krokodilerian** [comment]
@markvdb , is 2018 the quote, or is this for FOSDEM2018?

**Comment by markvdb** [comment]
Not going to happen. This is more of a hassle than an advantage. Some of the problems:
* renting so much expensive audio gear means plenty of checking on site for both the courier and us
* our rental partner already messed up once, not being able to deliver from one location

We'll just rely on our staff to take care of this. Faster, easier, cheaper.
