### ISSUE TITLE
Enable json directory listings with nginx_http_autoindex module (requires somewhat recent nginx as available in stretch)

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#78]
This enables json directory listings. See http://nginx.org/en/docs/http/ngx_http_autoindex_module.html for more info.

Useful for lightweight checking for files.

**Comment by SuperQ** [comment]
It looks like nginx installs are sprinkled around a bit.  I'm going to make a PR to move the nginx install to a separate role to avoid duplication.

**Comment by markvdb** [comment]
Do be careful, because the package might or might not be the same. We have our self compiled one with rtmp support, which is hugely important!

That's why I suggested not to touch this anymore for the 2017 edition. We just don't have the manpower for it.

Mark

**Comment by SuperQ** [comment]
Yes, I discovered the customization already.

**Comment by markvdb** [comment]
Now in debian testing and soon in stretch stable backports. See #98 .

**Comment by markvdb** [comment]
Not relevant anymore.
