### ISSUE TITLE
Braindump for monitoring

### ISSUE THREAD

**Issue by RichiH** [FOSDEM/video#8]
This is not an exhaustive list; I am tired.
- Expose in Prometheus format
- gauges for
  - frame rate
  - compression
  - audio level
  - bitrate
  - all alert states
- counters for
  - total transmitted data

**Comment by SuperQ** [comment]
Counters for detected changes, for example signal loss, dropped frames.

For video box metrics disk IO stats, network packet error counts (node_exporter)

**Comment by krokodilerian** [comment]
I wrote something simple that shows the stream, default to muted, and with an overlay with the audio levels, https://github.com/krokodilerian/fostest -> mon.sh. 

@RichiH, what's Prometeus?

**Comment by RichiH** [comment]
https://prometheus.io/ is what we use for all FOSDEM monitoring.

**Comment by markvdb** [comment]
All of this should also be in ansible as part of the video box, vocto, streamers and postprocessing rollouts.

**Comment by SuperQ** [comment]
Videobox monitoring:
* Disk activity
* Storage space
* Number of video dump files

**Comment by biot** [comment]
# Audio/video stream monitoring:
* running on one or more stream monitoring server
* grab UDP multicast stream, feed into ffmpeg client
* client configured with filters, extracting metadata
* metrics output on stdout
* prometheus client in Python, getting ffmpeg client on stdin

## Audio
* for each monitored stream, feed into ebur128 filter
* running on one or more stream monitoring server
* for each monitored stream, feed into ebur128 filter
** extract momentary loudness metadata
** no sound input translates to about -64 dB; ambient is about -30 dB

**Comment by markvdb** [comment]
This main stuff has been implemented. Thank you for that. I'll create a separate ticket for the internal video streams. Those just moved from udp multicast to tcp unicast.
