### ISSUE TITLE
more recorded files per day

### ISSUE THREAD

**Issue by yoe** [FOSDEM/video#80]
sreview works better if there are multiple recorded files per room per day, rather than a single one for the whole day as is the case now; this would allow review to be started as soon as content has been recorded, rather than at the end of the day. In turn, this would allow speakers to do the review of their talk almost immediately after finishing it. Something along the following lines would be sufficient:

- enable `record_max_frames`, setting it to, say, 300*(frames per second).
- set `record_interval` to zero
- disable the creation of the .flv.mp4 files
- disable the nginx-mp4 module (or what its name was again). Pseudocutting is not necessary if files are sufficiently small.
- (optionally) enable NFS export for the review servers, so that sreview can have file access rather than having to go through HTTP (which would get us rid of one copy operation).

I haven't tested this at all though, so presumably someone needs to check whether it is properly working as expected.

**Comment by yoe** [comment]
is this going to happen for 2018?

**Comment by krokodilerian** [comment]
I don't see a reason why not. We need to run a few tests to see if there will be something like dropped frames/av-desync, and I hate NFS, but is definitely worth trying.

**Comment by yoe** [comment]
I didn't say drop the MP4 files, I said drop the nginx MP4 module (the one that allows getting part of a file through HTTP requests). I can do the same thing through crafted ffmpeg commands, and I'd need less temp storage doing it that way

**Comment by yoe** [comment]
Actually, you're right, I did say that :-)

Don't remember; I guess I might have thought it would waste less time that way

**Comment by krokodilerian** [comment]
Done.
