### ISSUE TITLE
Audio delay in Open Media devroom

### ISSUE THREAD

**Issue by cmassiot** [FOSDEM/video#82]
Hi, some talks (if not all) of the Open Media devroom have a very noticeable audio delay. We didn't have that when monitoring. Is it fixable?

**Comment by yoe** [comment]
This isn't the right place to report that issue.

If you received the review emails of the relevant talks, the review system has now been updated to incorporate an A/V sync feature, which should allow you to fix the issue.

Closing this bug here, since this repository has nothing to do with review.
