### ISSUE TITLE
overflow room

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#84]
People suggested an overflow room.

Not sure if there is much improvement to be found in that, as we had 20 rooms overflowing...

**Comment by krokodilerian** [comment]
There are some options for this:

* A TV in front of each room (not for all, as the corridors somewhere are too small) would be the closest thing. CCC used to do that at BCC.
* Overflow rooms in each building, that can be switched to one of the rooms from this building. This will not scale very well. And having rooms for overflow in a different building than the one with the talk is close to useless with the size of the campus.
* Any way for people to watch the talks over the network that doesn't kill it (jpegs that refresh every 3-4 seconds, and audio). Or broadcast over one wifi channel of all streams that everyone can connect to and use to watch (probably impossible).
* Insane idea like FM radio (although there isn't enough spectrum for it)
* DECT, again like CCC.

**Comment by RichiH** [comment]
> Any way for people to watch the talks over the network that doesn't kill it (jpegs that refresh every 3-4 seconds, and audio).

A stream with very slow frame rate might work.

> Or broadcast over one wifi channel of all streams that everyone can connect to and use to watch (probably impossible).

Not possible.

**Comment by markvdb** [comment]
We're not going to use anything else. We will actively point people at the streams:
* QR codes next to the ROOM FULL sign? Geert, could you take care of that?
* FOSDEM companion apps. I will look into those.

**Comment by ghosty-be** [comment]
There is already a QR code next to the open/closed sign and it points to https://video.fosdem.org
See:
http://ghosty.be/FOSDEM/2016/A4-signs-design/devroom_full.pdf

**Comment by markvdb** [comment]
Great, thx. Very glad to have that confirmed!

Only tangentially related: it would probably be a good idea to have as much of signage as possible in a git repo. Increasing the bus factor and things...

**Comment by ghosty-be** [comment]
Those are also in git, I believe graphics and then signage or something (this is just a link to my local copy :) )
