### ISSUE TITLE
(live) comments on video (stream) page

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#85]
This might be nice to have as feedback to the speaker.

**Comment by krokodilerian** [comment]
Personally I would hate it, as most of these have no moderation and become mostly crap very fast (see youtube, people suck and are mean). An option is to integrate webirc and channels like #fosdem-room, but all of them would require monitoring by someone with OP status.

**Comment by RichiH** [comment]
We did that in the past, it worked well without direct supervision. And we always have #fosdem for people to ask for ops in. We need to prepare channel and op list well in advance, though. I used to do those in batch when I was still staff, but mere mortals are rate-limited and have upper bounds on channel registrations.

**Comment by SuperQ** [comment]
Having per-room IRC/matrix would be good for sending alerts to.

**Comment by RichiH** [comment]
Valid point "Someone in room x do y" scales horizontally.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by markvdb** [comment]
We'll include a suggestion to have someone monitor irc in the devroom manager guide.

**Comment by markvdb** [comment]
Fixed in 21b39b6
