### ISSUE TITLE
Move control.video.fosdem.org on-site

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#89]
It's a bit silly to generate a constant 300 mbps for that alone... Might want to keep the control server on site for that. Just one more laptop on the wine rack.

This might also help make the multicast more reliable...

**Comment by krokodilerian** [comment]
It's not related to multicasting, it fetches stuff from vocto over tcp. Will work a bit better with less latency, though.

**Comment by krokodilerian** [comment]
This was done.
