### ISSUE TITLE
UDP multicast test scenario

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#9]
In the ideal scenario, Vasil wants 5 Mbit/box. That would mean 10 Mbit/room in U. Doable? What about UDP multicast?

Wouter S will investigate and confirm. See https://github.com/FOSDEM/video/tree/master/software#faking-a-stream-from-a-videobox for faking something very very close to videobox output.

Two fallback scenarios:
* Fall back to 2 Mbit/box. throw the separate streams at vocto in K. My favorite fallback. --Mark
* Keep 5 Mbit/box. Local vocto server. Throw pip stream directly to the streaming servers. --What could possibly go wrong with this one? --Mark

**Comment by krokodilerian** [comment]
Because the main recording point is the vocto (the boxes are mostly backup/last resort), having a vocto box close to the boxes is somewhat more reliable and should be looked into.

Also note this is UDP, so if the network is less than stellar, it'll lead to degradation in the streaming quality.

**Comment by markvdb** [comment]
@corosuske , See above for a minimal test scenario.

I will have a few combinations of voctops and real video boxes ready by next week too if you want. These don't take a lot of space. If you want (and you have a decent kensington lock to lock a source laptop input to something), this way you could do a bit closer to a real life test.

@gerryd , @krokodilerian , any further input on this?

**Comment by corosuske** [comment]
10MBPS might be the upper limit in some of the U building, for all the other rooms 100 MBPS should the minimum network

**Comment by krokodilerian** [comment]
@corosuske , do we know which parts of the U building are those, e.g. which rooms are going to be on 10mbps? Currently we do 4mbps per stream, if there's more than one room on a 10mbps pipe, i need to reconsider this (or run cables :) ).

**Comment by corosuske** [comment]
@krokodilerian no we will always only put one room/port 

i will verify tomorrow

**Comment by corosuske** [comment]
speed should be 100Mbps/room

**Comment by corosuske** [comment]
all seems to work 

will leave a RPI3 pluged into video Vlan on the U builidng 

did get some errors (see under) 


root@irregularapocalypse:/home/wouter# mpv udp://227.0.0.2:9000
Playing: udp://227.0.0.2:9000
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: non-existing PPS 0 referenced                                                                                         
[ffmpeg/video] h264: decode_slice_header error                                                                                             
[ffmpeg/video] h264: no frame!                                                                                                             
[ffmpeg/video] h264: non-existing PPS 0 referenced                                                                                         
[ffmpeg/video] h264: non-existing PPS 0 referenced                                                                                         
[ffmpeg/video] h264: decode_slice_header error                                                                                             
[ffmpeg/video] h264: no frame!                                                                                                             
[ffmpeg/video] h264: non-existing PPS 0 referenced                                                                                         
[ffmpeg/video] h264: non-existing PPS 0 referenced                                                                                         
[ffmpeg/video] h264: decode_slice_header error                                                                                             
[ffmpeg/video] h264: no frame!                                                                                                             
[ffmpeg/video] h264: non-existing PPS 0 referenced                                                                                         
[ffmpeg/video] h264: non-existing PPS 0 referenced                                                                                         
[ffmpeg/video] h264: decode_slice_header error                                                                                             
[ffmpeg/video] h264: no frame!
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 --alang=und (aac)
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
AV: 00:00:08 A-V:  0.000 Dropped: 5 Cache:  1s+0KB

**Comment by gerryd** [comment]
@corosuske: splendid! Many thanks for checking! I'll sleep better now. :)
