### ISSUE TITLE
video vlan network connection at H infodesk for H building video team

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#92]
This was solved for 2017 by pulling a cable from H2215 to infodesk, but that's clearly not ideal...

**Comment by krokodilerian** [comment]
This was fixed, and will be requested from network this year.

**Comment by markvdb** [comment]
We would like 4 points with video network connectivity:
 * U near Chavanne
 * U back behind the square (**new requirement for 2019**)
 * AW
 * H

**Comment by markvdb** [comment]
Closing. Merging this into one networking request in  #91.
