### ISSUE TITLE
nginx rtmp in Debian

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#98]
Relevant bits from Debian:

* Existing list of nginx modules: http://sources.debian.net/src/nginx/1.11.9-1~exp2/debian/modules/README.Modules-versions/
* No new modules are being accepted into Debian for nginx since 2015: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790623#20
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797812 : request dismissed as wontfix
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843777#10 : request dismissed as wontfix; upstream author labeled as unreliable contact
* Nginx recently grew support for dynamically loadable modules, but that's not enough yet: https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/
* The nginx rtmp module is the prime example of a complex nginx module being converted to a dynamically loadable module: https://www.nginx.com/resources/wiki/extending/converting/

**Comment by markvdb** [comment]
After discussion with h0lger and olasd on irc.oftc.net#debian-devel , I sent this message to 843777@bugs.debian.org . It seems to have been eaten by their spam filter for now, so pasting here for now:
```
Hello,

> Both of these bugs are being merged with our no-new-modules bucket. We
> are working to allow any number of new modules, in the future; we're
> not there, yet. When we do get there, these bugs will be expected to
> be filed as ITP/RFP's. ;)

At https://fosdem.org , we are using the nginx rtmp module
intensively. It seems it is becoming a de facto standard when an
in-house streaming server is preferred, as opposed to an external
streaming platform. It combines excellently with ffmpeg, the recently
pacakged voctomix and several components of the gstreamer framework,
to create an excellent FOSS video streaming stack. Some debconf video
people too seem to be interested...

I've watched upstream nginx development for a bit. Dynamically loaded
modules are supported since 1.9.11, but separate module compilation
doesn't look like it is going to happen anytime soon.

Would you be willing to temporarily reconsider the ban on the
inclusion of a small set of new nginx modules into Debian until this
situation changes? If it helps, it seems like at least the rtmp module
could be done as a dynamically loaded module at least...

https://www.nginx.com/resources/wiki/extending/converting/
https://www.nginx.com/blog/dynamic-modules-development/

Thank you for your work on Debian!
```

I also sent the following to owner@bugs.debian.org:
```
Hello,

My name is Mark Van den Borre. I co-organise https://fosdem.org . Coud
you please confirm that this message has reached you well?

As per the instructions in https://www.debian.org/Bugs/Reporting under
"Spam fighting and missing mail", I am contacting you regarding my
addition to bug #843777 .

Attached to this message, you will find the original message that I
tried to send to 843777@bugs.fosdem.org . I suspect it might have
ended up in some spam filter. Can you do something about that? Is
there anything I can do to help solve this?

Looking forward to an quick and efficient reply.

Kind regards,

Mark
```

Let's see what comes of it...

**Comment by markvdb** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843777 now updated.

**Comment by markvdb** [comment]
Poked people on irc.oftc.net#debconf-video and irc.oftc.net#debian-nginx once more now Debian Buster/10 development has opened up.

Christos Trochalakis (debian nginx maintainer team) promised to have a look at it this weekend. Nicolas Dandrimont (olasd, debconf-video) was faster and submitted a patch. If all goes well, this may go into stable backports very soon too. Fingers crossed...

**Comment by markvdb** [comment]
The module is in unstable and testing now.

https://packages.debian.org/search?keywords=libnginx-mod-rtmp&searchon=names&suite=all&section=all

I will jockey for an inclusion in stretch-backports, so we can actually use vanilla debian stable for FOSDEM 2018.

**Comment by krokodilerian** [comment]
I just upgraded to it, and it seems to work fine :)

**Comment by markvdb** [comment]
Now available in stretch-backports. Yay!

Finally closing this one...
